AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CovidTestLocator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: covidTestLocator.lambda_handler
      Runtime: python3.7
      CodeUri: s3://covid-test-locator/246f812b1bae713f16018b0baa4d08c2
